# Install wireless support along with a static configuration file.
FROM quay.io/centos-bootc/centos-bootc:stream9
RUN dnf -y install NetworkManager-wifi NetworkManager-wwan wpa_supplicant wireless-regdb && dnf clean all
# And also inject a config file.  This pattern of using the COPY command
# to inject an "overlay" for /etc can easily be extended to add multiple
# config files.
COPY etc /etc
